import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { AuthProvider } from "./components/AuthProvider";
import { ToastContainer } from "react-toastify";
import { EdgeStoreProvider } from "@/lib/edgestore/edgestore";

export const metadata = {
  title: "Habit Tracker",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        <AuthProvider>
          <EdgeStoreProvider>{children}</EdgeStoreProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
